# Workflow for releasing package to npm registry
name: Release to NPM
on:
    pull_request:
        types:
          - closed # Only run after PRs have been merged or closed
        branches:
          - main # Only run for PRs targeted against main branch

jobs:
    release:
        # Only run for pull requests that has been merged (not closed) and has the label "Release" attached
        if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'Release')) }}
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
              with:
                  ref: main
                  fetch-depth: 0
                  persist-credentials: false

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.15.x
                  registry-url: 'https://registry.npmjs.org' # This registry URL is necessary for publishing on NPM

            - name: Install Dependencies
              run: npm ci

            - name: Build Package
              run: npm run build

            - name: Release Package
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # need this to publish on NPM
                  GH_TOKEN: ${{ secrets.PLATFORM_READ_PRIVATE_REPOS }} # need this to push files automatically to Git
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # need this to create GitHub Release
              run: |
                  npx semantic-release
